/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace Client {
  export type EVMTokenAmountStruct = {
    token: AddressLike;
    amount: BigNumberish;
  };

  export type EVMTokenAmountStructOutput = [token: string, amount: bigint] & {
    token: string;
    amount: bigint;
  };

  export type Any2EVMMessageStruct = {
    messageId: BytesLike;
    sourceChainSelector: BigNumberish;
    sender: BytesLike;
    data: BytesLike;
    destTokenAmounts: Client.EVMTokenAmountStruct[];
  };

  export type Any2EVMMessageStructOutput = [
    messageId: string,
    sourceChainSelector: bigint,
    sender: string,
    data: string,
    destTokenAmounts: Client.EVMTokenAmountStructOutput[]
  ] & {
    messageId: string;
    sourceChainSelector: bigint;
    sender: string;
    data: string;
    destTokenAmounts: Client.EVMTokenAmountStructOutput[];
  };
}

export declare namespace CrossChainExpenseSplitterPTT {
  export type CrossChainPaymentStruct = {
    expenseId: BytesLike;
    debtor: AddressLike;
    amount: BigNumberish;
    fromToken: BigNumberish;
    toToken: BigNumberish;
    sourceChain: BigNumberish;
  };

  export type CrossChainPaymentStructOutput = [
    expenseId: string,
    debtor: string,
    amount: bigint,
    fromToken: bigint,
    toToken: bigint,
    sourceChain: bigint
  ] & {
    expenseId: string;
    debtor: string;
    amount: bigint;
    fromToken: bigint;
    toToken: bigint;
    sourceChain: bigint;
  };
}

export interface CrossChainExpenseSplitterPTTInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "CCIP_BNM"
      | "USDC"
      | "acceptOwnership"
      | "ccipReceive"
      | "contributeLocal"
      | "contributeWithPTT"
      | "createExpense"
      | "decodeDirectPayment"
      | "decodeExpensePayment"
      | "expenses"
      | "getExpenseDetails"
      | "getRouter"
      | "hasUserPaid"
      | "owner"
      | "payRecipient"
      | "supportsInterface"
      | "transferOwnership"
      | "userContributions"
      | "withdraw"
      | "withdrawToken"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "ContributionMade"
      | "CrossChainPaymentReceived"
      | "DirectPaymentReceived"
      | "DirectPaymentSent"
      | "ExpenseCreated"
      | "ExpenseSettled"
      | "OwnershipTransferRequested"
      | "OwnershipTransferred"
      | "TokenSwapped"
  ): EventFragment;

  encodeFunctionData(functionFragment: "CCIP_BNM", values?: undefined): string;
  encodeFunctionData(functionFragment: "USDC", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "acceptOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "ccipReceive",
    values: [Client.Any2EVMMessageStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "contributeLocal",
    values: [BytesLike, AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "contributeWithPTT",
    values: [
      BytesLike,
      BigNumberish,
      AddressLike,
      BigNumberish,
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "createExpense",
    values: [BytesLike, BigNumberish, string, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "decodeDirectPayment",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "decodeExpensePayment",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "expenses", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "getExpenseDetails",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "getRouter", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "hasUserPaid",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "payRecipient",
    values: [
      AddressLike,
      BigNumberish,
      AddressLike,
      BigNumberish,
      BigNumberish,
      string
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "userContributions",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "withdraw",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawToken",
    values: [AddressLike, AddressLike]
  ): string;

  decodeFunctionResult(functionFragment: "CCIP_BNM", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "USDC", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "acceptOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ccipReceive",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "contributeLocal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "contributeWithPTT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createExpense",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "decodeDirectPayment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "decodeExpensePayment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "expenses", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getExpenseDetails",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getRouter", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "hasUserPaid",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "payRecipient",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "userContributions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "withdraw", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "withdrawToken",
    data: BytesLike
  ): Result;
}

export namespace ContributionMadeEvent {
  export type InputTuple = [
    expenseId: BytesLike,
    contributor: AddressLike,
    amount: BigNumberish,
    isLocal: boolean,
    tokenType: BigNumberish
  ];
  export type OutputTuple = [
    expenseId: string,
    contributor: string,
    amount: bigint,
    isLocal: boolean,
    tokenType: bigint
  ];
  export interface OutputObject {
    expenseId: string;
    contributor: string;
    amount: bigint;
    isLocal: boolean;
    tokenType: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CrossChainPaymentReceivedEvent {
  export type InputTuple = [
    expenseId: BytesLike,
    contributor: AddressLike,
    amount: BigNumberish,
    fromToken: BigNumberish,
    toToken: BigNumberish
  ];
  export type OutputTuple = [
    expenseId: string,
    contributor: string,
    amount: bigint,
    fromToken: bigint,
    toToken: bigint
  ];
  export interface OutputObject {
    expenseId: string;
    contributor: string;
    amount: bigint;
    fromToken: bigint;
    toToken: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DirectPaymentReceivedEvent {
  export type InputTuple = [
    payer: AddressLike,
    recipient: AddressLike,
    amount: BigNumberish,
    fromToken: BigNumberish,
    paymentId: string
  ];
  export type OutputTuple = [
    payer: string,
    recipient: string,
    amount: bigint,
    fromToken: bigint,
    paymentId: string
  ];
  export interface OutputObject {
    payer: string;
    recipient: string;
    amount: bigint;
    fromToken: bigint;
    paymentId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DirectPaymentSentEvent {
  export type InputTuple = [
    payer: AddressLike,
    recipient: AddressLike,
    amount: BigNumberish,
    fromToken: BigNumberish,
    paymentId: string,
    messageId: BytesLike
  ];
  export type OutputTuple = [
    payer: string,
    recipient: string,
    amount: bigint,
    fromToken: bigint,
    paymentId: string,
    messageId: string
  ];
  export interface OutputObject {
    payer: string;
    recipient: string;
    amount: bigint;
    fromToken: bigint;
    paymentId: string;
    messageId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ExpenseCreatedEvent {
  export type InputTuple = [
    expenseId: BytesLike,
    creator: AddressLike,
    totalAmount: BigNumberish,
    settlementToken: AddressLike
  ];
  export type OutputTuple = [
    expenseId: string,
    creator: string,
    totalAmount: bigint,
    settlementToken: string
  ];
  export interface OutputObject {
    expenseId: string;
    creator: string;
    totalAmount: bigint;
    settlementToken: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ExpenseSettledEvent {
  export type InputTuple = [
    expenseId: BytesLike,
    totalAmount: BigNumberish,
    recipient: AddressLike
  ];
  export type OutputTuple = [
    expenseId: string,
    totalAmount: bigint,
    recipient: string
  ];
  export interface OutputObject {
    expenseId: string;
    totalAmount: bigint;
    recipient: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferRequestedEvent {
  export type InputTuple = [from: AddressLike, to: AddressLike];
  export type OutputTuple = [from: string, to: string];
  export interface OutputObject {
    from: string;
    to: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [from: AddressLike, to: AddressLike];
  export type OutputTuple = [from: string, to: string];
  export interface OutputObject {
    from: string;
    to: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TokenSwappedEvent {
  export type InputTuple = [
    fromToken: AddressLike,
    toToken: AddressLike,
    fromAmount: BigNumberish,
    toAmount: BigNumberish
  ];
  export type OutputTuple = [
    fromToken: string,
    toToken: string,
    fromAmount: bigint,
    toAmount: bigint
  ];
  export interface OutputObject {
    fromToken: string;
    toToken: string;
    fromAmount: bigint;
    toAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface CrossChainExpenseSplitterPTT extends BaseContract {
  connect(runner?: ContractRunner | null): CrossChainExpenseSplitterPTT;
  waitForDeployment(): Promise<this>;

  interface: CrossChainExpenseSplitterPTTInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  CCIP_BNM: TypedContractMethod<[], [string], "view">;

  USDC: TypedContractMethod<[], [string], "view">;

  acceptOwnership: TypedContractMethod<[], [void], "nonpayable">;

  ccipReceive: TypedContractMethod<
    [message: Client.Any2EVMMessageStruct],
    [void],
    "nonpayable"
  >;

  contributeLocal: TypedContractMethod<
    [
      expenseId: BytesLike,
      token: AddressLike,
      amount: BigNumberish,
      tokenType: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  contributeWithPTT: TypedContractMethod<
    [
      expenseId: BytesLike,
      destinationChainSelector: BigNumberish,
      tokenIn: AddressLike,
      amountIn: BigNumberish,
      fromToken: BigNumberish,
      toToken: BigNumberish
    ],
    [string],
    "payable"
  >;

  createExpense: TypedContractMethod<
    [
      expenseId: BytesLike,
      totalAmount: BigNumberish,
      description: string,
      settlementToken: AddressLike
    ],
    [void],
    "nonpayable"
  >;

  decodeDirectPayment: TypedContractMethod<
    [data: BytesLike],
    [
      [string, string, string, bigint, bigint, string] & {
        action: string;
        recipient: string;
        payer: string;
        amount: bigint;
        fromToken: bigint;
        paymentId: string;
      }
    ],
    "view"
  >;

  decodeExpensePayment: TypedContractMethod<
    [data: BytesLike],
    [
      [string, CrossChainExpenseSplitterPTT.CrossChainPaymentStructOutput] & {
        action: string;
        payment: CrossChainExpenseSplitterPTT.CrossChainPaymentStructOutput;
      }
    ],
    "view"
  >;

  expenses: TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, bigint, bigint, boolean, string, string] & {
        creator: string;
        totalAmount: bigint;
        amountPaid: bigint;
        settled: boolean;
        description: string;
        settlementToken: string;
      }
    ],
    "view"
  >;

  getExpenseDetails: TypedContractMethod<
    [expenseId: BytesLike],
    [
      [string, bigint, bigint, boolean, string, string] & {
        creator: string;
        totalAmount: bigint;
        amountPaid: bigint;
        settled: boolean;
        description: string;
        settlementToken: string;
      }
    ],
    "view"
  >;

  getRouter: TypedContractMethod<[], [string], "view">;

  hasUserPaid: TypedContractMethod<
    [arg0: BytesLike, arg1: AddressLike],
    [boolean],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  payRecipient: TypedContractMethod<
    [
      recipient: AddressLike,
      destinationChainSelector: BigNumberish,
      tokenIn: AddressLike,
      amountIn: BigNumberish,
      fromToken: BigNumberish,
      paymentId: string
    ],
    [string],
    "payable"
  >;

  supportsInterface: TypedContractMethod<
    [interfaceId: BytesLike],
    [boolean],
    "view"
  >;

  transferOwnership: TypedContractMethod<
    [to: AddressLike],
    [void],
    "nonpayable"
  >;

  userContributions: TypedContractMethod<
    [arg0: BytesLike, arg1: AddressLike],
    [bigint],
    "view"
  >;

  withdraw: TypedContractMethod<
    [beneficiary: AddressLike],
    [void],
    "nonpayable"
  >;

  withdrawToken: TypedContractMethod<
    [beneficiary: AddressLike, token: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "CCIP_BNM"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "USDC"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "acceptOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "ccipReceive"
  ): TypedContractMethod<
    [message: Client.Any2EVMMessageStruct],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "contributeLocal"
  ): TypedContractMethod<
    [
      expenseId: BytesLike,
      token: AddressLike,
      amount: BigNumberish,
      tokenType: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "contributeWithPTT"
  ): TypedContractMethod<
    [
      expenseId: BytesLike,
      destinationChainSelector: BigNumberish,
      tokenIn: AddressLike,
      amountIn: BigNumberish,
      fromToken: BigNumberish,
      toToken: BigNumberish
    ],
    [string],
    "payable"
  >;
  getFunction(
    nameOrSignature: "createExpense"
  ): TypedContractMethod<
    [
      expenseId: BytesLike,
      totalAmount: BigNumberish,
      description: string,
      settlementToken: AddressLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "decodeDirectPayment"
  ): TypedContractMethod<
    [data: BytesLike],
    [
      [string, string, string, bigint, bigint, string] & {
        action: string;
        recipient: string;
        payer: string;
        amount: bigint;
        fromToken: bigint;
        paymentId: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "decodeExpensePayment"
  ): TypedContractMethod<
    [data: BytesLike],
    [
      [string, CrossChainExpenseSplitterPTT.CrossChainPaymentStructOutput] & {
        action: string;
        payment: CrossChainExpenseSplitterPTT.CrossChainPaymentStructOutput;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "expenses"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, bigint, bigint, boolean, string, string] & {
        creator: string;
        totalAmount: bigint;
        amountPaid: bigint;
        settled: boolean;
        description: string;
        settlementToken: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getExpenseDetails"
  ): TypedContractMethod<
    [expenseId: BytesLike],
    [
      [string, bigint, bigint, boolean, string, string] & {
        creator: string;
        totalAmount: bigint;
        amountPaid: bigint;
        settled: boolean;
        description: string;
        settlementToken: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getRouter"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "hasUserPaid"
  ): TypedContractMethod<
    [arg0: BytesLike, arg1: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "payRecipient"
  ): TypedContractMethod<
    [
      recipient: AddressLike,
      destinationChainSelector: BigNumberish,
      tokenIn: AddressLike,
      amountIn: BigNumberish,
      fromToken: BigNumberish,
      paymentId: string
    ],
    [string],
    "payable"
  >;
  getFunction(
    nameOrSignature: "supportsInterface"
  ): TypedContractMethod<[interfaceId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[to: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "userContributions"
  ): TypedContractMethod<
    [arg0: BytesLike, arg1: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "withdraw"
  ): TypedContractMethod<[beneficiary: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "withdrawToken"
  ): TypedContractMethod<
    [beneficiary: AddressLike, token: AddressLike],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "ContributionMade"
  ): TypedContractEvent<
    ContributionMadeEvent.InputTuple,
    ContributionMadeEvent.OutputTuple,
    ContributionMadeEvent.OutputObject
  >;
  getEvent(
    key: "CrossChainPaymentReceived"
  ): TypedContractEvent<
    CrossChainPaymentReceivedEvent.InputTuple,
    CrossChainPaymentReceivedEvent.OutputTuple,
    CrossChainPaymentReceivedEvent.OutputObject
  >;
  getEvent(
    key: "DirectPaymentReceived"
  ): TypedContractEvent<
    DirectPaymentReceivedEvent.InputTuple,
    DirectPaymentReceivedEvent.OutputTuple,
    DirectPaymentReceivedEvent.OutputObject
  >;
  getEvent(
    key: "DirectPaymentSent"
  ): TypedContractEvent<
    DirectPaymentSentEvent.InputTuple,
    DirectPaymentSentEvent.OutputTuple,
    DirectPaymentSentEvent.OutputObject
  >;
  getEvent(
    key: "ExpenseCreated"
  ): TypedContractEvent<
    ExpenseCreatedEvent.InputTuple,
    ExpenseCreatedEvent.OutputTuple,
    ExpenseCreatedEvent.OutputObject
  >;
  getEvent(
    key: "ExpenseSettled"
  ): TypedContractEvent<
    ExpenseSettledEvent.InputTuple,
    ExpenseSettledEvent.OutputTuple,
    ExpenseSettledEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferRequested"
  ): TypedContractEvent<
    OwnershipTransferRequestedEvent.InputTuple,
    OwnershipTransferRequestedEvent.OutputTuple,
    OwnershipTransferRequestedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "TokenSwapped"
  ): TypedContractEvent<
    TokenSwappedEvent.InputTuple,
    TokenSwappedEvent.OutputTuple,
    TokenSwappedEvent.OutputObject
  >;

  filters: {
    "ContributionMade(bytes32,address,uint256,bool,uint8)": TypedContractEvent<
      ContributionMadeEvent.InputTuple,
      ContributionMadeEvent.OutputTuple,
      ContributionMadeEvent.OutputObject
    >;
    ContributionMade: TypedContractEvent<
      ContributionMadeEvent.InputTuple,
      ContributionMadeEvent.OutputTuple,
      ContributionMadeEvent.OutputObject
    >;

    "CrossChainPaymentReceived(bytes32,address,uint256,uint8,uint8)": TypedContractEvent<
      CrossChainPaymentReceivedEvent.InputTuple,
      CrossChainPaymentReceivedEvent.OutputTuple,
      CrossChainPaymentReceivedEvent.OutputObject
    >;
    CrossChainPaymentReceived: TypedContractEvent<
      CrossChainPaymentReceivedEvent.InputTuple,
      CrossChainPaymentReceivedEvent.OutputTuple,
      CrossChainPaymentReceivedEvent.OutputObject
    >;

    "DirectPaymentReceived(address,address,uint256,uint8,string)": TypedContractEvent<
      DirectPaymentReceivedEvent.InputTuple,
      DirectPaymentReceivedEvent.OutputTuple,
      DirectPaymentReceivedEvent.OutputObject
    >;
    DirectPaymentReceived: TypedContractEvent<
      DirectPaymentReceivedEvent.InputTuple,
      DirectPaymentReceivedEvent.OutputTuple,
      DirectPaymentReceivedEvent.OutputObject
    >;

    "DirectPaymentSent(address,address,uint256,uint8,string,bytes32)": TypedContractEvent<
      DirectPaymentSentEvent.InputTuple,
      DirectPaymentSentEvent.OutputTuple,
      DirectPaymentSentEvent.OutputObject
    >;
    DirectPaymentSent: TypedContractEvent<
      DirectPaymentSentEvent.InputTuple,
      DirectPaymentSentEvent.OutputTuple,
      DirectPaymentSentEvent.OutputObject
    >;

    "ExpenseCreated(bytes32,address,uint256,address)": TypedContractEvent<
      ExpenseCreatedEvent.InputTuple,
      ExpenseCreatedEvent.OutputTuple,
      ExpenseCreatedEvent.OutputObject
    >;
    ExpenseCreated: TypedContractEvent<
      ExpenseCreatedEvent.InputTuple,
      ExpenseCreatedEvent.OutputTuple,
      ExpenseCreatedEvent.OutputObject
    >;

    "ExpenseSettled(bytes32,uint256,address)": TypedContractEvent<
      ExpenseSettledEvent.InputTuple,
      ExpenseSettledEvent.OutputTuple,
      ExpenseSettledEvent.OutputObject
    >;
    ExpenseSettled: TypedContractEvent<
      ExpenseSettledEvent.InputTuple,
      ExpenseSettledEvent.OutputTuple,
      ExpenseSettledEvent.OutputObject
    >;

    "OwnershipTransferRequested(address,address)": TypedContractEvent<
      OwnershipTransferRequestedEvent.InputTuple,
      OwnershipTransferRequestedEvent.OutputTuple,
      OwnershipTransferRequestedEvent.OutputObject
    >;
    OwnershipTransferRequested: TypedContractEvent<
      OwnershipTransferRequestedEvent.InputTuple,
      OwnershipTransferRequestedEvent.OutputTuple,
      OwnershipTransferRequestedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "TokenSwapped(address,address,uint256,uint256)": TypedContractEvent<
      TokenSwappedEvent.InputTuple,
      TokenSwappedEvent.OutputTuple,
      TokenSwappedEvent.OutputObject
    >;
    TokenSwapped: TypedContractEvent<
      TokenSwappedEvent.InputTuple,
      TokenSwappedEvent.OutputTuple,
      TokenSwappedEvent.OutputObject
    >;
  };
}
